content:
  - name: changelogs
    label: Changelogs
    path: pages/changelogs
    type: collection
    fields:
      - view:
        fields: [ title ]
        primary: title
        sort: [ date, title ]
        default:
          search: ''
          sort: title
          order: desc
